### ISSUE TITLE
script creates file in top directory

### ISSUE THREAD

**Issue by wcgall** [adobe-type-tools/keyboard-layouts#1]
I know no Python, so blame me for not making a 1-line edit.
This script attempts to create a file in the top directory, leading to a permissions error.
To avoid running as superuser, & for convenience, it would seem preferable to create the output file in the same directory as the script or input file.

**Comment by frankrolf** [comment]
Should be fixed by the above PR. Sorry for not commenting sooner, this issue was not on my radar at all.
